/**
 * Convia Blueprint 2.0 — Canonical Data Contract & Type Specification (Phase 2)
 * Comprehensive TypeScript contracts for Blueprint 2.0 execution models,
 * legacy Blueprint 1.x compatibility, authority matrix, and schema versioning.
 */

// ============================================================================
// 1. SCHEMA VERSIONING & AUTHORITY CLASSIFICATIONS
// ============================================================================

export const SCHEMA_VERSIONS = {
  LEGACY_V1: 1,
  CANONICAL_V2: 2,
  CURRENT: 2,
} as const;

export type SchemaVersion = 1 | 2;

/**
 * Authority Model Classifications:
 * - AI_PROPOSED: Generated by AI reasoning; subject to user or app review.
 * - APPLICATION_CONTROLLED: Managed deterministically by the Convia backend/RTDB layer.
 * - USER_CONTROLLED: Authoritative user actions, manual edits, assignments, or approvals.
 */
export const AUTHORITY = {
  AI_PROPOSED: 'AI_PROPOSED',
  APPLICATION_CONTROLLED: 'APPLICATION_CONTROLLED',
  USER_CONTROLLED: 'USER_CONTROLLED',
} as const;

export type AuthorityLevel = (typeof AUTHORITY)[keyof typeof AUTHORITY];

export type BlueprintLifecycleStatus =
  | 'not_created'
  | 'draft'
  | 'generating'
  | 'completed'
  | 'failed'
  | 'stale';

export type ModificationSource =
  | 'ai_generation'
  | 'manual'
  | 'hybrid'
  | 'migration';

// ============================================================================
// 2. ENUMS & LITERAL TYPES
// ============================================================================

export type RequirementType =
  | 'functional'
  | 'nonFunctional'
  | 'technical'
  | 'security'
  | 'performance'
  | 'business';

export type RequirementPriority =
  | 'Critical'
  | 'Must Have'
  | 'Should Have'
  | 'Nice to Have'
  | 'Low';

export type RequirementSource =
  | 'ai_inferred'
  | 'mvp_proposal'
  | 'discussion_decision'
  | 'user_specified';

export type RequirementStatus =
  | 'proposed'
  | 'accepted'
  | 'deferred'
  | 'rejected';

export type FeaturePriority = 'Must Have' | 'Should Have' | 'Nice to Have';
export type FeatureStatus = 'planned' | 'in_development' | 'completed';

export type DecisionCategory =
  | 'architecture'
  | 'technology'
  | 'database'
  | 'security'
  | 'scope'
  | 'hosting';

export type DecisionConfidence = 'high' | 'medium' | 'low';
export type DecisionSource = 'ai_recommended' | 'user_defined';

export type RoleAssignmentStatus =
  | 'unassigned'
  | 'recommended'
  | 'assigned'
  | 'insufficient_data';

export type TaskCategory =
  | 'setup'
  | 'frontend'
  | 'backend'
  | 'database'
  | 'api'
  | 'security'
  | 'testing'
  | 'devops'
  | 'deployment'
  | 'documentation'
  | 'design'
  | 'research'
  | 'infrastructure'
  | 'qa'
  | 'general';

export type TaskPriority = 'Critical' | 'High' | 'Medium' | 'Low';
export type TaskExecutionStatus =
  | 'Todo'
  | 'In Progress'
  | 'Review'
  | 'Completed'
  | 'Blocked';

export type DependencyType = 'blocks' | 'blockedBy' | 'dependsOn' | 'relatedTo';

export type AcceptanceCriterionType =
  | 'functional'
  | 'technical'
  | 'security'
  | 'performance'
  | 'ux';

export type AcceptanceCriterionStatus = 'pending' | 'passed' | 'failed';

export type RiskCategory =
  | 'technical'
  | 'security'
  | 'dependency'
  | 'operational'
  | 'schedule'
  | 'product';

export type SeverityLevel = 'Critical' | 'High' | 'Medium' | 'Low';
export type LikelihoodLevel = 'High' | 'Medium' | 'Low';
export type RiskStatus = 'identified' | 'mitigated' | 'accepted' | 'closed';

export type ReadinessLevel =
  | 'Ready for Development'
  | 'Needs Refinement'
  | 'Incomplete Concept';

export type AiRecommendationCategory =
  | 'architecture'
  | 'product'
  | 'performance'
  | 'security'
  | 'workflow'
  | 'team'
  | 'scalability'
  | 'futureEnhancement';

export type AiRecommendationStatus = 'proposed' | 'accepted' | 'dismissed';

// ============================================================================
// 3. CANONICAL ENTITY DEFINITIONS
// ============================================================================

// ----------------------------------------------------------------------------
// A. Project Understanding
// ----------------------------------------------------------------------------
export interface MvpScopeBoundaries {
  inScope: string[];
  outOfScope: string[];
  successCriteria: string[];
}

export interface ProjectUnderstanding {
  summary: string;
  vision: string;
  problemStatement: string;
  targetAudience: string;
  proposedSolution: string;
  valueProposition: string;
  mvpScope: MvpScopeBoundaries;
  assumptions: string[];
  constraints: string[];
}

// ----------------------------------------------------------------------------
// B. Requirements
// ----------------------------------------------------------------------------
export interface RequirementItem {
  id: string; // e.g. "REQ-01"
  title: string;
  description: string;
  type: RequirementType;
  priority: RequirementPriority;
  source: RequirementSource;
  status: RequirementStatus;
  category?: string;
}

// ----------------------------------------------------------------------------
// C. Architecture & Technical Decisions
// ----------------------------------------------------------------------------
export interface TechnologyStack {
  frontend: string[];
  backend: string[];
  database: string[];
  hosting: string[];
  thirdPartyApis: string[];
  evaluationReason: string;
}

export interface ArchitectureDecision {
  id: string; // e.g. "ADR-01"
  category: DecisionCategory;
  decision: string;
  rationale: string;
  alternatives: string[];
  tradeOffs: string;
  consequences: string;
  confidence: DecisionConfidence;
  source: DecisionSource;
}

export interface DatabaseEntitySchema {
  entityName: string;
  entityType: 'Necessary Entity' | 'Optional Entity';
  isOptional: boolean;
  description?: string;
  fields: string[];
  optionalFields: string[];
}

export interface DataArchitecture {
  primaryDatabase: string;
  entities: DatabaseEntitySchema[];
}

export interface ArchitectureDecisions {
  architecturePattern: string;
  components: string[];
  dataFlowDescription: string;
  technologyStack: TechnologyStack;
  decisions: ArchitectureDecision[];
  dataArchitecture: DataArchitecture;
}

// ----------------------------------------------------------------------------
// D. Execution: Features, Workflow, Roles, Tasks, Dependencies, Timeline
// ----------------------------------------------------------------------------
export type ProficiencyLevel = 'beginner' | 'intermediate' | 'advanced' | 'expert';
export type CapabilitySource = 'userProvided' | 'verifiedProfile' | 'imported' | 'systemDerived';
export type WorkloadLevel = 'low' | 'balanced' | 'high' | 'overloaded' | 'unknown';

export interface UserCapability {
  skill: string;
  proficiency: ProficiencyLevel;
  source: CapabilitySource;
  verified: boolean;
}

export interface RequiredCapability {
  skill: string;
  minimumProficiency?: ProficiencyLevel;
  importance: 'required' | 'preferred';
}

export interface TaskAssignmentRecommendation {
  taskId: string;
  taskTitle: string;
  category?: TaskCategory;
  priority?: TaskPriority;
  recommendedRoleId: string | null;
  recommendedRoleName: string | null;
  currentAssignedUserId: string | null;
  currentAssignedUserName: string | null;
  recommendedUserId: string | null;
  recommendedUserName: string | null;
  matchScore: number;
  confidence: 'high' | 'medium' | 'low' | 'none';
  matchLevel: 'strong' | 'moderate' | 'weak' | 'unknown' | 'none';
  reasons: string[];
  capabilityMatches: Array<{
    skill: string;
    matchedSkill: string;
    memberProficiency: ProficiencyLevel;
    requiredProficiency: ProficiencyLevel;
    importance: 'required' | 'preferred';
    fit: 'meets_or_exceeds' | 'partial_proficiency';
  }>;
  capabilityGaps: Array<{
    skill: string;
    requiredProficiency?: ProficiencyLevel;
    importance: 'required' | 'preferred';
  }>;
  alternatives: Array<{
    memberId: string;
    memberName: string;
    matchScore: number;
    confidence: string;
    reasons: string[];
  }>;
  isCriticalPath: boolean;
  isBlocked: boolean;
  unmetPrerequisites: string[];
}

export interface MemberWorkloadStat {
  memberId: string;
  memberName: string;
  workspaceRole: string;
  activeTaskCount: number;
  completedTaskCount: number;
  totalEstimatedHours: number;
  overdueTaskCount: number;
  hasEffortData: boolean;
  assignedTaskIds: string[];
  workloadLevel: WorkloadLevel;
  workloadPercentage: number;
  capacity: 'unknown' | number;
}

export interface TeamExecutionSummary {
  workloadConcentration: string[];
  capabilityGaps: string[];
  uncoveredRoles: TeamRoleRecommendation[];
  unassignedCriticalTasksCount: number;
  teamCoveragePercentage: number;
  strategicAdvice: string[];
  membersWorkload?: MemberWorkloadStat[];
  totalProjectHours?: number;
  unassignedTaskCount?: number;
}

export interface FeatureItem {
  id: string; // e.g. "FEAT-01"
  name: string;
  description: string;
  priority: FeaturePriority;
  status: FeatureStatus;
  requirementIds: string[]; // references REQ-xx
  acceptanceCriteriaIds: string[]; // references AC-xx
  taskIds: string[]; // references TASK-xx
}

export interface WorkflowStep {
  id: string; // e.g. "WF-01"
  stepNumber: number;
  stepName: string;
  description: string;
  input: string;
  output: string;
  featureIds: string[]; // references FEAT-xx
  taskIds: string[]; // references TASK-xx
  dependencyStepIds: string[]; // references WF-xx
}

export interface TeamRoleRecommendation {
  id: string; // e.g. "ROLE-01"
  roleName: string;
  responsibility: string;
  capabilityRequirements: string[];
  recommendedUserId: string | null; // Nullable - skills not invented
  recommendedUserName: string | null;
  assignmentStatus: RoleAssignmentStatus;
  assignmentNote: string;
  taskIds: string[]; // references TASK-xx
}

export interface TaskItem {
  id: string; // e.g. "TASK-01"
  title: string;
  description: string;
  category: TaskCategory;
  priority: TaskPriority;
  status: TaskExecutionStatus;
  featureId: string | null; // references FEAT-xx
  requirementIds: string[]; // references REQ-xx
  workflowStepId: string | null; // references WF-xx
  recommendedRoleId: string | null; // references ROLE-xx
  assignedUserId: string | null; // Authoritative user/app state
  assignedUserName: string | null;
  dependencyIds: string[]; // references TASK-xx
  acceptanceCriteriaIds: string[]; // references AC-xx
  requiredCapabilities?: RequiredCapability[];
  assignmentRecommendation?: TaskAssignmentRecommendation;
  estimatedEffortHours: number | null;
  milestoneId: string | null; // references MILE-xx
  source: 'ai_proposed' | 'manual';
  isConvertedToTask: boolean; // True when exported/instantiated in RTDB tasks/
  convertedTaskId: string | null; // Reference to RTDB task node
}

export interface TaskDependency {
  id: string; // e.g. "DEP-01"
  sourceTaskId: string; // The prerequisite task ID (must finish first)
  targetTaskId: string; // The dependent task ID (blocked until source finishes)
  type: DependencyType;
  reason: string;
}

export interface MilestoneItem {
  id: string; // e.g. "MILE-01"
  name: string;
  description: string;
  order: number;
  duration: string; // e.g. "Sprint 1 (Week 1)"
  deliverables: string[];
  taskIds: string[]; // references TASK-xx
  status: 'planned' | 'in_progress' | 'completed';
}

export interface TimelinePlan {
  planningAssumptions: string[];
  estimatedDuration: string;
  milestones: MilestoneItem[];
  criticalPathTaskIds: string[];
}

export interface ExecutionModel {
  features: FeatureItem[];
  workflow: WorkflowStep[];
  roles: TeamRoleRecommendation[];
  tasks: TaskItem[];
  dependencies: TaskDependency[];
  timeline: TimelinePlan;
  teamExecutionSummary?: TeamExecutionSummary;
}

// ----------------------------------------------------------------------------
// E. Quality: Acceptance Criteria, Testing, Risks, DoD, Readiness
// ----------------------------------------------------------------------------
export interface AcceptanceCriterion {
  id: string; // e.g. "AC-01"
  description: string;
  type: AcceptanceCriterionType;
  status: AcceptanceCriterionStatus;
  relatedTaskId: string | null;
  relatedFeatureId: string | null;
}

export interface TestCaseItem {
  id: string; // e.g. "TC-01"
  title: string;
  category: 'unit' | 'integration' | 'api' | 'ui' | 'security' | 'performance' | 'e2e';
  description: string;
  relatedRequirementIds: string[];
  relatedFeatureIds: string[];
  relatedTaskIds: string[];
  targetVerification: string;
  status: 'planned' | 'verified' | 'unverified';
}

export interface TestCoverageSummary {
  totalRequirementsCount: number;
  coveredRequirementsCount: number;
  requirementCoveragePercentage: number;
  totalFeaturesCount: number;
  coveredFeaturesCount: number;
  featureCoveragePercentage: number;
  uncoveredCriticalRequirements: string[];
  uncoveredCriticalFeatures: string[];
}

export interface TestingStrategy {
  overview: string;
  unitTesting: TestSuiteScope;
  integrationTesting: TestSuiteScope;
  apiTesting: TestSuiteScope;
  uiTesting: TestSuiteScope;
  securityTesting: TestSuiteScope;
  performanceTesting: TestSuiteScope;
  e2eTesting: TestSuiteScope;
  testCases?: TestCaseItem[];
  testCoverageSummary?: TestCoverageSummary;
}

export interface RiskItem {
  id: string; // e.g. "RISK-01"
  title: string;
  description: string;
  category: RiskCategory;
  likelihood: LikelihoodLevel;
  impact: SeverityLevel;
  severity: SeverityLevel;
  mitigation: string;
  contingency: string;
  affectedFeatureIds?: string[];
  affectedTaskIds?: string[];
  affectedRequirementIds?: string[];
  ownerRoleId: string | null;
  ownerUserId?: string | null;
  relatedTaskIds?: string[];
  status: RiskStatus;
  source?: 'ai_proposed' | 'user_defined' | 'system_derived';
}

export type QualityGateStatus = 'not_started' | 'in_progress' | 'blocked' | 'passed' | 'failed' | 'waived';

export interface QualityGateItem {
  id: string; // e.g. "GATE-01"
  name: string;
  stage: number;
  description: string;
  status: QualityGateStatus;
  requiredEvidence: string[];
  actualEvidence: string[];
  blockers: string[];
  warnings: string[];
  isAutomated: boolean;
  verifiedAt: number | null;
  verifiedBy: string | null;
}

export interface DefinitionOfDone {
  developmentComplete: string[];
  testingCriteria: string[];
  securityChecks: string[];
  deploymentReadiness: string[];
  documentation: string[];
  operationalReadiness: string[];
}

export interface ProjectReadinessRating {
  score: number; // 0 - 100
  level: ReadinessLevel;
  gaps: string[];
}

export interface ProductionReadinessCategory {
  status: 'passed' | 'partial' | 'blocked' | 'unknown';
  summary: string;
}

export interface ProductionReadinessSummary {
  overallStatus: 'not_ready' | 'partially_ready' | 'ready_for_review' | 'ready_for_deployment' | 'production_ready';
  readinessScore: number;
  derivedLevel: string;
  categorySummaries: {
    requirements: ProductionReadinessCategory;
    architecture: ProductionReadinessCategory;
    execution: ProductionReadinessCategory;
    testing: ProductionReadinessCategory;
    security: ProductionReadinessCategory;
    deployment: ProductionReadinessCategory;
    operations: ProductionReadinessCategory;
  };
  blockers: string[];
  warnings: string[];
  passedChecks: string[];
  unknownChecks: string[];
}

export interface QualityModel {
  acceptanceCriteria: AcceptanceCriterion[];
  testingStrategy: TestingStrategy;
  risks: RiskItem[];
  qualityGates?: QualityGateItem[];
  definitionOfDone: DefinitionOfDone;
  readiness: ProjectReadinessRating;
  productionReadiness?: ProductionReadinessSummary;
}

// ----------------------------------------------------------------------------
// F. Intelligence: Discussions, Decisions, Recommendations, Backlog
// ----------------------------------------------------------------------------
export type DecisionStatus = 'proposed' | 'under_review' | 'approved' | 'rejected' | 'superseded' | 'reverted';
export type QuestionStatus = 'open' | 'answered' | 'resolved' | 'dismissed';
export type QuestionCategory = 'informational' | 'implementation' | 'requirement' | 'architecture' | 'decision_blocking' | 'execution_blocking';
export type SuggestionStatus = 'proposed' | 'under_review' | 'accepted' | 'rejected' | 'superseded' | 'implemented';
export type ChangeRecommendationStatus = 'proposed' | 'approved' | 'rejected' | 'applied' | 'stale';
export type ChangeTargetType = 'requirement' | 'feature' | 'task' | 'dependency' | 'milestone' | 'risk' | 'test' | 'architecture';
export type ChangeType = 'create' | 'modify' | 'remove' | 'clarify' | 'invalidate';

export interface DecisionRecord {
  id: string; // e.g. "DEC-01"
  title: string;
  decision: string;
  rationale: string;
  category: DecisionCategory;
  status: DecisionStatus;
  confidence?: 'high' | 'medium' | 'low';
  sourceDiscussionIds?: string[];
  sourceSuggestionIds?: string[];
  sourceQuestionIds?: string[];
  affectedRequirementIds?: string[];
  affectedFeatureIds?: string[];
  affectedTaskIds?: string[];
  affectedRiskIds?: string[];
  affectedTestIds?: string[];
  supersedesDecisionId?: string | null;
  supersededByDecisionId?: string | null;
  isScopeChange?: boolean;
  scopeChangeDescription?: string | null;
  createdBy?: string;
  createdByName?: string;
  approvedBy?: string | null;
  approvedByName?: string | null;
  approvedAt?: number | null;
  createdAt?: number;
  updatedAt?: number;
  source?: 'ai_proposed' | 'user_defined';

  // Backward compatibility fields
  sourceDiscussionId?: string | null;
  authorName?: string;
  impactArea?: string;
  timestamp?: number;
}

export interface AcceptedSuggestionRecord {
  id: string;
  content: string;
  suggestion?: string;
  authorName: string;
  status?: SuggestionStatus;
  isAccepted?: boolean;
  relevance: 'high' | 'medium' | 'low';
  impact?: string;
  reason?: string;
  recommendation?: string;
  implementedInFeatureId?: string | null;
  linkedDecisionId?: string | null;
  isScopeExpansion?: boolean;
  affectedProjectElements?: string[];
  createdAt?: number;
}

export interface RejectedSuggestionRecord {
  id: string;
  content: string;
  suggestion?: string;
  authorName: string;
  status?: SuggestionStatus;
  reason: string;
  affectedProjectElements?: string[];
  createdAt?: number;
}

export interface UnresolvedQuestionRecord {
  id: string; // e.g. "Q-01"
  question: string;
  authorName: string;
  status: QuestionStatus;
  category: QuestionCategory;
  isBlocking: boolean;
  suggestedOwnerRoleId?: string | null;
  recommendedNextAction?: string;
  sourceDiscussionId?: string | null;
  resolvedByDecisionId?: string | null;
  affectedRequirementIds?: string[];
  affectedFeatureIds?: string[];
  affectedTaskIds?: string[];
  createdAt?: number;

  // Backward compatibility fields
  area?: string;
  severity?: 'high' | 'medium' | 'low';
  suggestedResolution?: string;
}

export interface ImportantCommentRecord {
  id: string;
  content: string;
  authorName: string;
  insight: string;
  relevance: 'high' | 'medium' | 'low';
  createdAt?: number;
}

export interface ChangeRecommendationItem {
  id: string; // e.g. "CR-01"
  sourceDecisionId: string;
  targetType: ChangeTargetType;
  targetId: string;
  changeType: ChangeType;
  currentStateSummary: string;
  proposedChange: string;
  reason: string;
  impactSeverity: 'high' | 'medium' | 'low';
  downstreamImpactSummary?: string;
  status: ChangeRecommendationStatus;
  isStale: boolean;
  reviewedBy?: string | null;
  reviewedByName?: string | null;
  reviewedAt?: number | null;
  createdAt: number;
}

export interface DiscussionConflictRecord {
  topic: string;
  perspectives: string[];
  status: 'open' | 'resolved';
}

export interface DiscussionIntelligenceStats {
  totalDiscussions: number;
  suggestionsCount: number;
  questionsCount: number;
  commentsCount: number;
  decisionsCount: number;
  approvedDecisionsCount: number;
  openQuestionsCount: number;
  blockingQuestionsCount: number;
  pendingChangeRecommendationsCount: number;
}

export interface DiscussionIntelligence {
  summary: string;
  keyThemes?: string[];
  conflicts?: DiscussionConflictRecord[];
  decisions: DecisionRecord[];
  acceptedSuggestions: AcceptedSuggestionRecord[];
  rejectedSuggestions: RejectedSuggestionRecord[];
  unresolvedQuestions: UnresolvedQuestionRecord[];
  importantComments: ImportantCommentRecord[];
  changeRecommendations?: ChangeRecommendationItem[];
  statistics?: DiscussionIntelligenceStats;
}

export interface AiRecommendation {
  id: string; // e.g. "REC-01"
  title: string;
  description: string;
  rationale: string;
  category: AiRecommendationCategory;
  confidence: 'high' | 'medium' | 'low';
  impact: 'high' | 'medium' | 'low';
  status: AiRecommendationStatus;
}

export interface FutureBacklogItem {
  id: string; // e.g. "BACK-01"
  title: string;
  description: string;
  reason: string;
  priority: 'High' | 'Medium' | 'Low';
  relatedFeatureIds: string[];
}

export interface StrategicIntelligenceModel {
  discussionIntelligence: DiscussionIntelligence;
  recommendations: AiRecommendation[];
  futureBacklog: FutureBacklogItem[];
}

// ============================================================================
// 4. CANONICAL BLUEPRINT 2.0 CONTENT SCHEMA
// ============================================================================

export interface Blueprint2Content {
  schemaVersion: 2;
  projectUnderstanding: ProjectUnderstanding;
  requirements: RequirementItem[];
  architecture: ArchitectureDecisions;
  execution: ExecutionModel;
  quality: QualityModel;
  intelligence: StrategicIntelligenceModel;
}

// ============================================================================
// 5. CANONICAL BLUEPRINT 2.0 DOCUMENT (Root Database Record)
// ============================================================================

export interface BlueprintDocumentV2 {
  blueprintId: string;
  workspaceId: string;
  orgId: string;
  mvpIdeaId: string;
  ideaId: string;
  versionId?: string;
  activeVersionId?: string;
  activeVersionKey?: string;
  version: string; // e.g. "1.0", "2.0"
  schemaVersion: 2;
  status: BlueprintLifecycleStatus;
  lastModifiedSource: ModificationSource;
  
  // AI & Generation Metadata
  aiProvider: string | null;
  aiModel: string | null;
  generatedAt: number | null;
  updatedAt: number;
  createdAt: number;
  generatedBy: string | null;
  createdBy: string | null;
  updatedBy?: string | null;
  lastError?: string | null;
  generationStartedAt?: number | null;
  generationCompletedAt?: number | null;
  generationFailedAt?: number | null;

  // Idea Snapshot Data
  ideaTitle: string;
  problemStatement: string;
  description: string;
  techStack?: string;
  authorId: string;
  authorName: string;

  // Canonical V2 Structured Content
  content: Blueprint2Content;

  // Version History Map (Snapshots)
  versions?: Record<string, BlueprintDocumentV2 | any>;
}

// ============================================================================
// 6. LEGACY BLUEPRINT 1.X COMPATIBILITY CONTRACTS
// ============================================================================

export interface Legacy16SectionContent {
  projectOverview?: {
    summary?: string;
    vision?: string;
    targetAudience?: string;
  };
  mvpScope?: {
    inScope?: string[];
    outOfScope?: string[];
    successCriteria?: string[];
  };
  recommendedTechStack?: {
    frontend?: string[];
    backend?: string[];
    database?: string[];
    hosting?: string[];
    thirdPartyApis?: string[];
    evaluationReason?: string;
  };
  coreFeatures?: Array<{
    featureName: string;
    description: string;
    priority: 'Must Have' | 'Should Have' | 'Nice to Have';
  }>;
  userFlow?: Array<{
    stepNumber: number;
    stepName: string;
    description: string;
  }>;
  technicalArchitecture?: {
    architecturePattern?: string;
    components?: string[];
    dataFlowDescription?: string;
  };
  databaseDesign?: {
    primaryDatabase?: string;
    entities?: Array<{
      entityName: string;
      entityType?: string;
      isOptional?: boolean;
      fields?: string[];
      optionalFields?: string[];
    }>;
  };
  teamAllocation?: Array<{
    memberId?: string;
    memberName?: string;
    assignedRole?: string;
    recommendedTasks?: string[];
  }>;
  challengesAndDifficulties?: Array<{
    challenge: string;
    severity: 'High' | 'Medium' | 'Low';
    mitigationStrategy: string;
  }>;
  innovationAndDifferentiation?: {
    keyDifferentiators?: string[];
    marketAdvantage?: string;
  };
  developmentRoadmap?: Array<{
    phase: string;
    duration: string;
    deliverables: string[];
  }>;
  suggestionsAnalysis?: Array<{
    id?: string;
    content?: string;
    relevance?: 'high' | 'medium' | 'low' | 'irrelevant';
    reason?: string;
    impact?: string;
    recommendation?: string;
  }>;
  commentsAnalysis?: Array<{
    id?: string;
    content?: string;
    relevance?: 'high' | 'medium' | 'low' | 'irrelevant';
    reason?: string;
    insight?: string;
    recommendation?: string;
  }>;
  questionsAnalysis?: Array<{
    id?: string;
    content?: string;
    relevance?: 'high' | 'medium' | 'low' | 'irrelevant';
    reason?: string;
    area?: string;
    recommendation?: string;
  }>;
  communityInsightsSummary?: any;
  projectReadiness?: {
    score?: number;
    readinessLevel?: string;
    reasons?: string[];
    keyGaps?: string[];
  };
}

export interface LegacyBlueprintDocument {
  blueprintId: string;
  workspaceId: string;
  mvpIdeaId: string;
  version: string;
  schemaVersion?: 1;
  status: BlueprintLifecycleStatus;
  content?: Legacy16SectionContent;
  versions?: Record<string, any>;
  [key: string]: any;
}
